### ISSUE TITLE
Feature request: Event when a player completes a quest

### ISSUE THREAD

**Issue by noeppi-noeppi** [SaphieNyako/Feywild#10]
I would like to have an event fired on the forge event bus whenever a player completes a quest which passes the player and the quest completed and if present the next quest in line. This could for example be useful to get support for Feywild quests in [Bongo](https://www.curseforge.com/minecraft/mc-mods/bongo)

**Comment by Playelectro** [comment]
Thanks for the feedback 😊

The quest system will most likely to go through a redesing in the near future and we will keep this in mind while doing it.

**Comment by SaphieNyako** [comment]
1.2.4 has been released!
