### ISSUE TITLE
Mandragora and Right Click Harvest

### ISSUE THREAD

**Issue by tkrow** [SaphieNyako/Feywild#100]
### Minecraft version

1.16.5

### Feywild version

2.0.7

### Forge version

36.2.30

### The latest.log file

No log available

### Issue description

Attempts to create Mandagora result in harvesting the mandrake despite the honey cookie present in player's hand.

### Steps to reproduce

1. Fully grow a mandrake
2. Right click with a honey cookie with a right click harvest mod
3. Harvest mandake instead of create mandragora

### Other information

This is part of the Medieval Minecraft 1.16.5 modpack. The developer supposedly reported the issue to the FeyWild github sometime around Mar 27.

**Comment by SaphieNyako** [comment]
Besides right clicking there is also an option to make a summoning scroll. It's also stated in the book that some magic prevents the first option, so people can make a summoning scroll instead.
