### ISSUE TITLE
Crash on startup when sneak is bound to a mouse button

### ISSUE THREAD

**Issue by winauer** [SaphieNyako/Feywild#109]
### Minecraft version

1.16.5

### Feywild version

1.16.5-2.1.3

### Forge version

36.2.34

### The latest.log file

https://pastebin.com/j6LZb40W

### Issue description

Game crashes on startup when sneak is bound to a mouse button. A window with an error message pops up. The key number in the error message depends on which mouse button is assigned to sneak.

https://i.imgur.com/443XT3y.png

### Steps to reproduce

* Set sneak to a mouse button
* close game
* open game

### Other information

Mekanism and Mining gadgets had the same issue in the past. See: 
mekanism/Mekanism#5920
and
Direwolf20-MC/MiningGadgets#101

**Comment by SaphieNyako** [comment]
Update your graphic card and mouse drivers. 
Let me know if that works.

**Comment by winauer** [comment]
No, it's not a driver issue. The error message is misleading. It's because when you look for the sneak key you only handle keyboard keys.

https://github.com/SaphieNyako/Feywild/blob/20c0b75d10255f8f93e1eb7ab74d37a696254134/src/main/java/com/feywild/feywild/util/KeyboardHelper.java#L12

**Comment by SaphieNyako** [comment]
We had this issue before, and that was always the solution. 
I'll look into it.

**Comment by SaphieNyako** [comment]
Uploaded a possible fix (waiting for approval): 
https://www.curseforge.com/minecraft/mc-mods/feywild/files/4015654
Let me know if that works...I don't have a fancy mouse to test it with *^_^*

**Comment by winauer** [comment]
Yes, it works now. Thank you for the quick response.

**Comment by SaphieNyako** [comment]
Thank you for your report!
Issue was there for a long time, wish someone had pointed it out this way sooner!
