### ISSUE TITLE
Fey ore and gems lacks proper tags

### ISSUE THREAD

**Issue by Gronglegrowth** [SaphieNyako/Feywild#117]
### Minecraft version

1.19.2

### Feywild version

1.19.2-3.0.3

### Forge version

43.2.7

### The latest.log file

None

### Issue description

The fey gem ore is not tagged "forge:ores" nor are fey gems tagged "forge:gems"; for categorization and consistency, I think they should be.

**Comment by SaphieNyako** [comment]
next update 3.1.5 this will be added.
