### ISSUE TITLE
[1.19.2] Server crash on startup

### ISSUE THREAD

**Issue by DelviousCrafts** [SaphieNyako/Feywild#118]
### Minecraft version

1.19.2

### Feywild version

3.1.1

### Forge version

43.2.8

### The latest.log file

https://gist.github.com/DelviousCrafts/eca0d73ae39884ac07c7c13778840a97

### Issue description

Loading a server with Feywild latest version causes a crash on startup due to HumanoidModel attempt to load for dedicated server. Does not occur on version 3.1.0. Client is not affected.

Crash Report: 
[crash-2023-04-07_21.38.54-fml.txt](https://github.com/SaphieNyako/Feywild/files/11182535/crash-2023-04-07_21.38.54-fml.txt)

### Steps to reproduce

1. install latest feywild on server.
2. attempt to launch server
3. crash

**Comment by SaphieNyako** [comment]
Thank you for reporting!
Fix in 3.1.2 wich is being uploaded right now!
