### ISSUE TITLE
Creative flight in survival is broken completely with this loaded

### ISSUE THREAD

**Issue by Gronglegrowth** [SaphieNyako/Feywild#121]
### Minecraft version

1.19.2

### Feywild version

3.1.5

### Forge version

43.2.11

### The latest.log file

N/A

### Issue description

Updated the mod to 3.1.5 and found upon entering my main world, my flying was disabled (I was using the swiftwolf ring from ProjectE). I confirmed this mod was breaking it by disabling it, seeing the flying ring work again, and then enabling it, seeing it no longer do so. I don't have any other mods present which grant creative flight, but I imagine those methods would be broken too.

I suspect this has something to do with the fey wings changes?

### Steps to reproduce

1. obtain a method of creative flight in survival that is not from feywild (e.g. ProjectE swiftwolf ring)
2. attempt to fly
3. you just jump, flight is not activated

### Other information

ProjectE is on version 1.0.1B for 1.19.2.

**Comment by SaphieNyako** [comment]
Thanks for reporting, looking into it now.

**Comment by SaphieNyako** [comment]
Fix in next update 3.1.6
Cleaning up code and then I'll release it.
