### ISSUE TITLE
Server random crash

### ISSUE THREAD

**Issue by takezie** [SaphieNyako/Feywild#123]
### Minecraft version

1.19.2

### Feywild version

Feywild-1.19.2-3.2.2

### Forge version

1.19.2-43.2.14

### The latest.log file

https://pastebin.com/9aQm8Xb6

### Issue description

Server randomly crash, possibly caused with planted summer tree saplings we didnt grow to the tree?

### Steps to reproduce

I don't know what we did wrong

**Comment by takezie** [comment]
Just found abandoned summer sapling, so if player1 make the sibling quest, but then place another sapling and dont grow it, possibly it can crash server? I'll try to remove all sapling we planted.

**Comment by SaphieNyako** [comment]
fix in 3.2.3, releasing soon.

**Comment by SaphieNyako** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/feywild/files/4635218

This should fix it. If possible pls verify.
