### ISSUE TITLE
The Eternal Falls and Frozen Retreat literally do not exist.

### ISSUE THREAD

**Issue by Devintrainer** [SaphieNyako/Feywild#125]
### Minecraft version

1.19.2

### Feywild version

1.19.2-3.2.3

### Forge version

43.2.14

### The latest.log file

none, really

### Issue description

When exploring the Feywild dimension, I only see the Blossoming Wealds, Golden Seele Fields, and the dimension's ocean. I can 
walk to or teleport to where the Eternal Falls and Frozen Retreat are _supposed_ to be, either via commands or Nature's Compass, but I don't see any sign of either.

**Comment by SaphieNyako** [comment]
As feywild is reflection of the overworld. Travel to a cold biome and teleport from there.
