### ISSUE TITLE
Allow books the librarian can give to be customized

### ISSUE THREAD

**Issue by Gronglegrowth** [SaphieNyako/Feywild#127]
### Describe your idea

For better integration, have the librarian's list of books that it can give you be customized with a config or datapack (such as a tag). This way, books that are be in the pack but not available at the feywild library, can easily be made such.

**Comment by SaphieNyako** [comment]
We already have that...
<https://github.com/SaphieNyako/Feywild/blob/dev/1.19/src/main/resources/data/feywild/feywild_util/books.json>
