### ISSUE TITLE
Fey tree logs/woods are incorrectly tagged as planks, whereas fey tree planks are not

### ISSUE THREAD

**Issue by Gronglegrowth** [SaphieNyako/Feywild#128]
### Minecraft version

1.19.2

### Feywild version

1.19.2-3.2.5

### Forge version

43.2.14

### The latest.log file

N/A

### Issue description

The fey tree logs and woods are tagged as both planks, and logs/woods, so they can be used by recipes asking for planks.

Conversely, the fey tree planks, are not tagged as planks, and thus can't be used in recipes asking for them.

**Comment by SaphieNyako** [comment]
![logs](https://github.com/user-attachments/assets/593e50a2-6117-4ce0-bf28-74fe224f7c5f)
![planks](https://github.com/user-attachments/assets/69ec4681-60a6-4737-af9a-a712151dc70e)
