### ISSUE TITLE
/locate biome and Nature's compass often point to high in the air or deep underground

### ISSUE THREAD

**Issue by zckss** [SaphieNyako/Feywild#129]
### Minecraft version

1.19.2

### Feywild version

1.19.2-3.2.6

### Forge version

43.3.0

### The latest.log file

n/a

### Issue description

Using the built-in /locate biome command or the Nature's Compass item will often point the player to a location nearby but high in the sky.   While there are some limited differences in the below-ground portion of biomes, the primary reason players would want to find a specific biome is for quests or trees, and those only matter at the surface.

Since the main importance of the biome is the surface and below ground variation is largely invisible to the player, it would be helpful to have each vertical column only contain a single biome so that locate-type commands can point to a (X,Z) that has that biome at the surface.

### Steps to reproduce

1. Create a world and enter the Feywild.
2. Run "/locate biome feywild:XXX" to different biomes.
3. The result will likely be nearby in X and Z, but high or low in Y. This will often be in the same surface biome you ran the command from.

### Other information

NaturesCompass version: 1.19.2-1.10.0-forge

**Comment by SaphieNyako** [comment]
I noticed this too, but I don't know whats causing it. 
I gues cause there are small patches of the biome spawning. 
It sometimes happens with other mod's  biomes too, just with feywild more cause we only have 4.
