### ISSUE TITLE
Libraries not spawning?

### ISSUE THREAD

**Issue by MystralMeteor** [SaphieNyako/Feywild#131]
### Minecraft version

1.19.2

### Feywild version

1.19.2-3.2.6

### Forge version

43.3.7

### The latest.log file

N/A

### Issue description

I'm enjoying the mod! However, I'm stuck at the questline where I'm supposed to find a library. I cannot for the life of me find one. I've been using the JourneyMap mod, which have helped me find numerous fey trees and dwarf forges, but no matter how far I seem to travel into new chunks, none have appeared. I've scoured the nearby biomes they can spawn in using JM, but no luck whatsoever. Do I just have extremely bad luck? 

### Other information

All mods I'm using in this world:

Botania-1.19.2-440-FORGE.jar
Cucumber-1.19.2-6.0.10.jar
curios-forge-1.19.2-5.1.4.4.jar
Feywild-1.19.2-3.2.6.jar
geckolib-forge-1.19-3.1.40.jar
gravestone-1.19.2-1.0.10.jar
journeymap-1.19.2-5.9.7-forge.jar
jei-1.19.2-forge-11.6.0.1018.jar
LibX-1.19.2-4.2.8.jar
MysticalAgriculture-1.19.2-6.0.13.jar
Patchouli-1.19.2-77.jar
SandBox-1.19.2-1.0.1.jar
telepads-1.19.2-6.1.0.2.jar

**Comment by SaphieNyako** [comment]
They spawn. If you have to many mods that add biomes or structures they might become more rare. They spawn in plains mostly. 
You can change spawn rates of biomes and structures with a data pack. You can find how to do those on google or youtube. 
GL :)
