### ISSUE TITLE
When entering the main menu in a multi-mod environment, resource loading errors and crashes may occur

### ISSUE THREAD

**Issue by Sovina1991** [SaphieNyako/Feywild#132]
### Minecraft version

1.20.1

### Feywild version

Feywild-1.20.1-4.0.0

### Forge version

47.2.20

### The latest.log file

https://pastebin.com/3UFqdQBg

### Issue description

Starting the game in multi-mode and Chinese environments may result in resource loading errors. A large amount of garbled code and lost resource packages can cause crashes when attempting to enter the game.__

### Steps to reproduce

[minecraft-exported-crash-info-2024-02-14T12-21-10.zip](https://github.com/SaphieNyako/Feywild/files/14275230/minecraft-exported-crash-info-2024-02-14T12-21-10.zip)

**Comment by Sovina1991** [comment]
It has been determined that there is a conflict with the Jei module, and the problem will only occur when installed simultaneously with Jei

**Comment by SaphieNyako** [comment]
Possible fix in 4.0.1
I tested it myself on a server and everything loaded normally. 
I'll close this ones I get comfirmation it works.
