### ISSUE TITLE
Crash with Embeddium

### ISSUE THREAD

**Issue by Alrena** [SaphieNyako/Feywild#135]
### Minecraft version

1.19.2

### Feywild version

3.2.6

### Forge version

43.3.8

### The latest.log file

https://gist.github.com/Alrena/6be1ad016d7230d16902d8abdec0b4fc

### Issue description

A crash occurs when both Embeddium and Feywild are running, when a dwarven blacksmith is gone near. Presumably when the dwarven blacksmith spawns or enters memory.

Crash Log:
https://gist.github.com/Alrena/81fb3fd516b3482d6f8100e7ecf83f68

**Comment by Alrena** [comment]
I've made a duplicate report to the Embeddium issues page:
https://github.com/embeddedt/embeddium/issues/234

**Comment by Alrena** [comment]
Accidentally closed the issue, sorry ><

**Comment by SaphieNyako** [comment]
I cant recreate this...Closing if there is no update
