### ISSUE TITLE
Winter Pixie: Tree Quest

### ISSUE THREAD

**Issue by DonDespo1** [SaphieNyako/Feywild#136]
### Minecraft version

1.20.1

### Feywild version

1.20.1-4.0.1

### Forge version

47.2.20

### The latest.log file

Not neccessary

### Issue description

The Quest mentioned in the title doesn't complete. Regardless if i use bonemeal or not, i was 5 block away with the pixie and it's not complete

### Steps to reproduce

1. Summon Pixie
2. Command to stay
3. Place Winter sappling
4. Bonemeal Sapling or wait
5. if Tree has grown, try to claim the quest, not complete

**Comment by SaphieNyako** [comment]
I tested this and it works for me. 
![2024-11-13_16 57 12](https://github.com/user-attachments/assets/c82f6802-e046-48ef-ae69-943faf0bbbdc)

**Comment by SaphieNyako** [comment]
![2024-11-13_16 57 18](https://github.com/user-attachments/assets/5171e7d8-59c4-4d5b-850e-22dbf9a2ace4)
