### ISSUE TITLE
Dwarven forges can spawn waterlogged

### ISSUE THREAD

**Issue by son0fether** [SaphieNyako/Feywild#139]
### Minecraft version

1.20.1

### Feywild version

1.20.1-4.0.1

### Forge version

47.2.0

### The latest.log file

N/A

### Issue description

When a Dwarven Forge spawns in the ocean, underwater, it is mostly filled with water.
![2024-05-12_10 05 50](https://github.com/SaphieNyako/Feywild/assets/40579173/e44891a6-4b7a-46f0-9d95-9adac4e9dba6)

### Steps to reproduce

Create a world, find a dwarven forge underwater (night vision potions help).

### Other information

I have the mod Tectonic in this pack I'm working on, so worldgen is a little different in this pack, but it's all vanilla ocean biomes.

**Comment by muppetenergy** [comment]
i get this a ton in my server as well. it'd be super useful to have configs of spawn rates since they're very frequent

**Comment by SaphieNyako** [comment]
Since 1.18+ you cant make config for spawn since its all datapacked. So you can make a datapack and change the numbers for spawn, place and everythings.

**Comment by SaphieNyako** [comment]
Removed spawn and structure
