### ISSUE TITLE
1.19.2 very low fps with Oculus Shader

### ISSUE THREAD

**Issue by Edel-Lilies** [SaphieNyako/Feywild#140]
### Minecraft version

1.19.2

### Feywild version

Feywild-1.19.2-3.2.6

### Forge version

43.4.0

### The latest.log file

https://gist.github.com/Theoretical-Enday/ca3db31df6cf34e26d1675ac7a353c30

### Issue description

Causes very low fps when spawning underground dwarf structures。
embeddium-0.3.18+mc1.19.2   oculus-mc1.19.2-1.6.9  DrDestens+MinecraftShaders+v2.0.2.zip
![QQ截图20240618221431](https://github.com/SaphieNyako/Feywild/assets/73912246/a9623537-f425-4b91-8206-3ae6da5b36a7)
![QQ截图20240618221924](https://github.com/SaphieNyako/Feywild/assets/73912246/c496f406-98a4-4adb-8264-b4711cce630f)

After executing the command /kill @e ，Fps returns to normal

![QQ截图20240618222330](https://github.com/SaphieNyako/Feywild/assets/73912246/278082f4-adc1-44df-8f7f-1acc94c5e94b)

in world other side

**Comment by SaphieNyako** [comment]
Probably cause of the glow layer.
You can turn that off in config.
Other then that we dont give support for using shaders.
But i think disabling the glow in config should help. ☺️
