### ISSUE TITLE
Dwarves

### ISSUE THREAD

**Issue by meraspera** [SaphieNyako/Feywild#141]
### Minecraft version

1.20.1

### Feywild version

1.20.1-4.0.1

### Forge version

47.3.0

### The latest.log file

.

### Issue description

I'm playing on version 1.20.1 4.0.1. I have a base underground. Dwarves are constantly being born there. No matter how many times I kill them, they come back. I do not know what to do. I tried deleting the mod but my game crashes. Can't open without restoring.

### Steps to reproduce

.

### Other information

.

**Comment by SaphieNyako** [comment]
Removed spawn and structure
Fix in 4.0.3
