### ISSUE TITLE
When "summon all fey" config option is set to false, it becomes impossible to use summoning scrolls

### ISSUE THREAD

**Issue by Not-February** [SaphieNyako/Feywild#142]
### Minecraft version

1.20.1

### Feywild version

1.20.1-4.0.2

### Forge version

47.3.0

### The latest.log file

not relevant

### Issue description

If the config option is toggled to `false`, it becomes impossible to use pixie summoning scrolls _at all_, even if one has never summoned a fey nor aligned themselves with a court before attempting to use it.

If the config option is set to `true`(the default state), this issue does not occur.

I specifically noticed this while summoning an autumn pixie, but I suspect it happens with the other types too.

### Steps to reproduce

1. Set config option for ``summon_all_fey`` to false
2. Load into a new world
3. Try to use a pixie summoning scroll

**Comment by SaphieNyako** [comment]
This option should have been removed a while ago. 
It will be removed in next update: 4.0.3

It was a fun idea but not relevant for the current setup and futher direction of the mod. 
Do remove the old config file if updating.
