### ISSUE TITLE
Creative Tab Texture Issue

### ISSUE THREAD

**Issue by ChaosDogG** [SaphieNyako/Feywild#143]
### Minecraft version

1.20.1

### Feywild version

1.20.1-4.0.3

### Forge version

47.1.106

### The latest.log file

https://gist.github.com/ChaosDogG/a26a4e9372c91a3537b9be28ce82c40b

### Issue description

The Creative menu tab is borked, perhaps due to it being formatted for 1.19.3 and below when 1.19.4+ has since changed it, making it look spliced

### Steps to reproduce

1. Add mod, and perhaps a few others
2. Boot game
3. Make creative world
4. Open Creative menu and find the tab

### Other information

![2024-08-27_16 54 39](https://github.com/user-attachments/assets/753407af-9545-413e-b79c-e30389095590)

**Comment by SaphieNyako** [comment]
Removed the imaged Tab and replace it with a standard item. |
Fixed in 4.0.4
