### ISSUE TITLE
Right click ent crashes game

### ISSUE THREAD

**Issue by FunnyBunny14** [SaphieNyako/Feywild#144]
### Minecraft version

1.20.1

### Feywild version

Feywild -1.20.1 - 4.0.3 - Chapter 2

### Forge version

neoforge 47.1.106

### The latest.log file

https://pastebin.com/E5VJSd5y

### Issue description

Right click an ent, might need to be a second ent, or spring ent?
Then the game crashes, and the world can no longer be loaded because it crashes for the same reason

**Comment by SaphieNyako** [comment]
Fix in next update 4.0.4
