### ISSUE TITLE
Supplementaries and Macaw windows glitch out with feywild

### ISSUE THREAD

**Issue by Mr-Syntax** [SaphieNyako/Feywild#17]
it doesent crash the game or anything its just that, when i loaded it first some trees had ropes from supplementaries instead of leaves and when i removed it, it switched to windows from macaw windows instead

so i guess they must have some overlapping ID or something

anyway pretty cool didnt try much yet but the visuals look really good

**Comment by Playelectro** [comment]
You are talking about the leaves added by feywild or just leaves in general?

**Comment by Mr-Syntax** [comment]
![image](https://user-images.githubusercontent.com/59544236/126051268-124bec13-d49b-44dd-9b5c-f6463fe1125e.png)

**Comment by Mr-Syntax** [comment]
the leaves on these trees seem to conflict with macaw and supllementaries, the yellow leaves from feywilds work tho

**Comment by SaphieNyako** [comment]
I work with the same mods for ModPack and don't have issues. Did you update from older versions to new? Cause this happens when your world gets corrupted.

**Comment by Mr-Syntax** [comment]
i have biomes o plenty installed but i have no idea what would be causing it cause i have 230 mods running :D

**Comment by SaphieNyako** [comment]
Yeh what Im trying to say is that your world got corrupted cause you added to the world that already excisted. 
No mod hardcodes ids. Yours just got scrambled. 
Its no fault of Supplementaries, Macaw or Feywild.
You just cant always add to a excisting world. Thats why you get a message that things might not work properly if they are not part of the orginal set up. 
So its best to set it back to the point where you didnt have problems and play with those mods.
And if you want to extend make a new world. 
Otherwise you risk curropting it like this.

**Comment by Mr-Syntax** [comment]
but this happend consistently on new worlds, im not really playing atm i just boot it create a new seed and fly around in creative to see if it works cause i have 234 mods running together so it can be a little tricky to get working

**Comment by Playelectro** [comment]
Hmm might be caused by another mod interfering but that is still a bit far fetched.... tbh I have no idea why this is happening since it should be impossible, it's not like macaw's named their panels feywild:autumn_tree_leaves or something

**Comment by SaphieNyako** [comment]
Do you have a download for your mod pack?

**Comment by SaphieNyako** [comment]
Feywild feywild-1.16.5-1.2.3.jar
GeckoLib geckolib-forge-1.16.5-3.0.42.jar
Macaw's Bridges mcw-bridges-1.0.6-mc1.16.5.jar
Macaw's Doors mcw-doors-1.0.3-mc1.16.5.jar
Macaw's Fences and Walls mcw-fences-1.0.0-mc1.16.5.jar
Macaw's Furniture mcw-furniture-2.0.1-mc1.16.5.jar
Macaw's Lights and Lamps mcw-lights-1.0.0-mc1.16.5.jar
Macaw's Paintings  mcw-paintings-1.0.2-mc1.16.5.jar
Macaw's Roofs mcw-roofs-2.0.1-mc1.16.5-4.jar
Macaw's Trapdoors mcw-trapdoors-1.0.2-mc1.16.5.jar
Macaw's Windows mcw-windows-1.0.3-mc1.16.5.jar
Patchouli Patchouli-1.16.4-53.1.jar
Selene selene-1.16.5-1.5.jar
Supplementaries supplementaries-1.16.5-0.14.5.jar

Tried these mods and it all works fine, so you can say it are not these mods. So you only have 220 more mods to test to find the culprid XD
