### ISSUE TITLE
Crash without report

### ISSUE THREAD

**Issue by InteJason** [SaphieNyako/Feywild#21]
https://pastebin.com/9BKdUEMS

Experienced this crash in a server, strange thing is it creates a crash report without writing anything on it. On the console it clearly states that it's caused by feywild.

Version: 1.2.4, for forge 1.16.5

**Comment by SaphieNyako** [comment]
Thanks for reporting!
We currently cleaning our code, this will be tackled next update.

**Comment by SaphieNyako** [comment]
new update.
