### ISSUE TITLE
Crash With "DwarfBlacksmithEntity" on the "magma server"

### ISSUE THREAD

**Issue by OcrSu** [SaphieNyako/Feywild#25]
I'm not sure whose fault it is
So I gave feedback on both sides.

crash log:https://paste.ubuntu.com/p/2b4gHky8kV/
Feywild:1.2.4
Forge:36.2.2
Magma: Magma Dev HEAD-4874525 (https://github.com/magmafoundation/Magma-1.16.x)
Java:11
OS:Win10 X64

**Comment by noeppi-noeppi** [comment]
Looks like this is an issue with Magma

**Comment by OcrSu** [comment]
OK,thank you!
