### ISSUE TITLE
Crash when generating world 

### ISSUE THREAD

**Issue by chevy7895** [SaphieNyako/Feywild#27]
So I attempted to add FeyWild to a mod pack, it results in a crash every time a single player world is created. Attached is the crash log. The Error code for the game crash is " The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchFieldError: FEY_GEM_BLOCK
Exit Code: -1"

Not sure if it is mod interaction or what but hope this helps 
[LFP T2 - Fey Wild upload -1.7.10.zip](https://github.com/SaphieNyako/Feywild/files/7035925/LFP.T2.-.Fey.Wild.upload.-1.7.10.zip)

[crash-2021-08-23_20.00.08-client.txt](https://github.com/SaphieNyako/Feywild/files/7035910/crash-2021-08-23_20.00.08-client.txt)

**Comment by SaphieNyako** [comment]
Thanks for reporting. 
We dont use the annotation FEY_GEM_BLOCK in the new version 
`com.thevortex.allthemodium.worldgen.miningdimension.Feytures`
Does allthemodium mod add the block? 

They made an update for that: 
https://www.curseforge.com/minecraft/mc-mods/allthemodium/files/3437133
