### ISSUE TITLE
Summer Tree Logs Drop birch wood

### ISSUE THREAD

**Issue by WolfDM** [SaphieNyako/Feywild#28]
I made a mod pack and when I mine a summer tree it drops Birch wood instad of the summer tree logs

**Comment by noeppi-noeppi** [comment]
This is intended. Use silk touch to get the summer wood

**Comment by SaphieNyako** [comment]
Q: When I cut down the trees I get normal blocks I think this is a glitch!

A: This is how its suppose to work. They fey trees are normal trees imbued with magic. When you cut them down they loose this magic. 
You could try silk touch if you want the fey log itself! 

:D
