### ISSUE TITLE
the newest version on 1.16.5 forge 36.2.0 crashes with immersive portals

### ISSUE THREAD

**Issue by Mr-Syntax** [SaphieNyako/Feywild#31]
[crash-2021-09-12_05.59.13-server.txt](https://github.com/SaphieNyako/Feywild/files/7149027/crash-2021-09-12_05.59.13-server.txt)

**Comment by SaphieNyako** [comment]
Thanks for your report.
I dont see feywild on the modlist in this crash report.

Ran a test myself and it seems to work. 
But first give a crash report with feywild please.

**Comment by noeppi-noeppi** [comment]
Also please remove OptiFine and Performant before reporting such issues. These are not open source, it's not really known what they do exactly and we can do nothing about it if it does not happen without them. So if removing either of them helps, please report to their author.

**Comment by SaphieNyako** [comment]
crash report without feywild on the mod list.
