### ISSUE TITLE
Feywild Structure waystone not present with Charm Reforged

### ISSUE THREAD

**Issue by AngleWyrm10** [SaphieNyako/Feywild#32]
There used to be a waystone next to the library, but after adding some mods it no longer appears.

**Comment by SaphieNyako** [comment]
wich mods did you add?
and did you perhaps change the config?

**Comment by AngleWyrm10** [comment]
I saw that there was support for some mods so I added Botania and  Ars Nouveau. I've also added a bunch of other mods that weren't mentioned on the SourceForge description page. 

If it helps any, here's a directory listing of my current mods folder, about 200 mods: [dir.txt](https://github.com/SaphieNyako/Feywild/files/7274776/dir.txt)

I don't recall changing the config file(s) for Feywild, but I'm hopelessly forgetful. I do remember editing config files for Advanced Compass and FTBChunks to get the death markers to work together properly.

**Comment by SaphieNyako** [comment]
Did you add the new mods to an excisting world?

**Comment by AngleWyrm10** [comment]
**Testing Plan:** Create new world, hop on a magic broom and scout for a Library

- Created four default worlds with Biomes'O'Plenty worldgen; two crashed during world gen so I left those for dead. I scouted the other two in a 1000m x 1000m area, but didn't find any libraries.
- Created another new world using Terraforged worldgen and found a library immediately.

The highlighted area is where I remember finding a waystone during previous playthroughs 
(I was using Terraforged back then as well)
![library](https://user-images.githubusercontent.com/55937426/135871775-5c1f752e-0761-42ba-aacd-7d4f0a790a15.png)


Directory listing of mods folder at the time: [dir.txt](https://github.com/SaphieNyako/Feywild/files/7278819/dir.txt)
 Config/Feywild folder: [feywild.zip](https://github.com/SaphieNyako/Feywild/files/7278924/feywild.zip)

**Comment by SaphieNyako** [comment]
So finding the culprit should go as follows:
Test it with feywild and waystone and see if it works.
If it does great then its nothing we caused.
Then start adding the mods(maybe 20 by 20 to save time)
If it breaks its one of those mods and narrow it down. 
Then we know what mod and we can look into this closer.
Also send a copy of your config please.

**Comment by AngleWyrm10** [comment]
I've spent a couple hours scouting on my magic broom, but haven't come across any more libraries.
This testing process is too expensive for me to repeat.

**Comment by SaphieNyako** [comment]
Thank you for your services, Kiki! 
You can also use /locate feywild:library
And go to another place using /locatebiome

Tested with waystones and feywild and it works. 

After testing 50 of the mods
I found the culprit: **charm-forge-1.16.5-2.3.2.jar**
wich is quit a big mod to go through......but atleast we know who is causing it.

Thanks for reporting

**Comment by SaphieNyako** [comment]
Blacksmith is also missing waystones.
Waystones spawn normally in the world and villages.

**Comment by SaphieNyako** [comment]
Issue created for Charm Forge:
https://github.com/svenhjol/CharmForge/issues/131

**Comment by AngleWyrm10** [comment]
Great job! I'm gonna disable Charm Reforged for now, until the status of them [fixing that NBT null bug](https://github.com/svenhjol/CharmForge/issues/131) changes
