### ISSUE TITLE
Mandragora disappears if I leave the area

### ISSUE THREAD

**Issue by AngleWyrm10** [SaphieNyako/Feywild#33]
The Mandragora disappears if I leave the area; the bee knight does not. I even made a nametag and labelled one Punkin 'cause she had a pumpkin skirt. But when I returned from a trip to the Nether she had disappeared from the fenced off garden.

Discord discussion reply from Ancient_Spirit

> oh no did we forget to set the perssistent tag? yes we did
> hmm it also seems that the mandragora doesn't remember it's type...
> Thank you for reporting this is definitely a bug

**Comment by SaphieNyako** [comment]
update coming in a min :D

**Comment by AngleWyrm10** [comment]
awesomeness;
now you have a mission complete button :)

**Comment by SaphieNyako** [comment]
This should be fixed in feywild 2.0.2
