### ISSUE TITLE
Feywild requires version that is valid but reports that it isn't

### ISSUE THREAD

**Issue by VallenFrostweaver** [SaphieNyako/Feywild#35]
Minecraft 1.16.5
Forge 36.2.2
Feywild 1.16.5-2.0.2
LibX 1.16.3-1.0.76
Supplementaries 1.16.5-0.15.2b

The pack crashes to this screen:
![image](https://user-images.githubusercontent.com/13642054/138455774-14535bde-c247-49df-86fe-861ba06c3b6c.png)

I have this version installed:
![image](https://user-images.githubusercontent.com/13642054/138455811-23910996-3138-442d-894f-c60b2f12cb7f.png)

I has a confuse.

**Comment by noeppi-noeppi** [comment]
That's a supplementaries problem. They have their version the the JAR manifest set wrongly for this file. Report it there please. We can set the version to `1.16.5-0.15.0` in the mods.toml file but that is a dirty hack. The real problem is on supplementaries side here.
