### ISSUE TITLE
Incorrect dependencies has Forge supporting mods grabbing Fabric ones and crashing

### ISSUE THREAD

**Issue by VallenFrostweaver** [SaphieNyako/Feywild#36]
Minecraft 1.16.5
Forge 36.2.2
Feywild 1.16.5-2.0.2
LibX 1.16.3-1.0.76

I verified this with the GDLauncher devs and have sent a DM to Saphie as this likely crashes any new Forge installs with Feywild
![image](https://user-images.githubusercontent.com/13642054/138456667-69e9d8d7-532a-4550-99af-9c78d338404a.png)

**Comment by noeppi-noeppi** [comment]
The problem seems to be that the files are not tagged as `Forge` on CurseForge (Except for `2.0`).

**Comment by SaphieNyako** [comment]
Changed the tag to forge!

**Comment by SaphieNyako** [comment]
This doesnt do the trick sadly. It still picks the fabric version for some reason. 
Also on older versions that do have the forge tag it still picks the fabric version
