### ISSUE TITLE
When i have signposts enabled it seems to lag everything out

### ISSUE THREAD

**Issue by Mr-Syntax** [SaphieNyako/Feywild#38]
i think its because i put the distance between villages so high in my pack and when it attempts to find a village for the sign it will lag completely

it crashed 2 times on me because of a memory leak untill i disabled signposts in the config

https://www.curseforge.com/minecraft/modpacks/chosencraft

i all ready had it disabled but when i updated the issue when it generated the new config

**Comment by SaphieNyako** [comment]
Hello...
I actually have no idea what this is about. What does this have to do with our mod: Feywild.

**Comment by SaphieNyako** [comment]
![2021-10-27_17 55 02](https://user-images.githubusercontent.com/77398437/139102259-a2bd35e3-d417-4453-b383-fa17cbdfb5cb.png)

Do you mean these sign posts? 
If so they are from Supplementaries.
Feywild doesnt use sign posts.

**Comment by MehVahdJukaar** [comment]
Hi, since this is probably meant for me might I ask what Supplementaries version you are using?

**Comment by Mr-Syntax** [comment]
wups accidently loaded the wrong site, but yes in supplementaries

**Comment by MehVahdJukaar** [comment]
eehm so what version?

**Comment by SaphieNyako** [comment]
wrong mod.
