### ISSUE TITLE
LibX 2.19 or higher needed for Feywild 1.17 - Crash

### ISSUE THREAD

**Issue by SHXRKIEgg** [SaphieNyako/Feywild#39]
Hi, I'm trying to add feywild to my Medieval Minecraft 1.17.1 Modpack and im getting this crash.
Changing Libx to latest alpha fixes it, is that fine to use in my Modpack or wait for an update?

Crash - https://pastebin.com/BSc380Hs

**Comment by SaphieNyako** [comment]
Feywild is set to only work with 2.19 or higher of LibX. 
Gues curseforge picks the non alpha version...
So yes you can !

**Comment by SaphieNyako** [comment]
Correct version is added now automatically.
