### ISSUE TITLE
[1.16.5] Supplementaries version dependency

### ISSUE THREAD

**Issue by drakray** [SaphieNyako/Feywild#44]
Excerpt
```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[forge:?] {re:classloading}
-- MOD feywild --
Details:
	Mod File: b-03-feywild-2.0.6.jar
	Failure message: Mod feywild only supports supplementaries 1.16.5-0.16.0 or above
		Currently, supplementaries is 0.17.12
	Mod Version: 1.16.5-2.0.6
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
```
Full crashlog https://pastebin.com/kKWKqQ8L

**Comment by SaphieNyako** [comment]
Tested this. 
The 12 version has a b behind it. 
I reported it to the creator of supplementaries. 
Hopefully a newer version will come soon

**Comment by drakray** [comment]
I "fixed" it locally by changing the mods.toml `version="0.17.12"` to `version="1.16.5-0.17.12"` in the supplementaries jar, and it work now

**Comment by SaphieNyako** [comment]
The creator just comfirmed that too !
Im closing this then.

**Comment by starmun-0010** [comment]
Please fix this dependency issue, it is really hard to include Feywild  in modpacks because of this reason.
Cannot do the local version change fix when shipping a modpack.

**Comment by SaphieNyako** [comment]
I was waiting for the creator of supplementaries to change the way they do their version numbering. But I removed the dependency completely, since he added our pixies to the mods' tags. So this shouldnt be a problem in new version 2.0.7
