### ISSUE TITLE
Feywild is incompatible with Just Enough Resources

### ISSUE THREAD

**Issue by CloudMeow** [SaphieNyako/Feywild#46]
I add Feywild and Just Enough Resources into my modpack .When I search the drop of mobs , It’s useless . Other mods are incompatible with JER.
emmm......Should I report to Just Enough Resources？

**Comment by CloudMeow** [comment]
Feywild version : 1.16.5-2.0.7

**Comment by SaphieNyako** [comment]
![2021-12-08_11 58 43](https://user-images.githubusercontent.com/77398437/145197066-0fd8372c-bde8-43e1-b32e-a910d225b469.png)

Hey! I'm not sure what's expected. 
But this seems to work when I try it.

**Comment by CloudMeow** [comment]
> 

emmm，tell me the version of JER please . I will try aging . I really want play the nice mod with my friend

**Comment by SaphieNyako** [comment]
JustEnoughResources-1.16.5-0.12.1.133.jar
Hope it works for you!

**Comment by CloudMeow** [comment]
JER without Feywild
![without](https://user-images.githubusercontent.com/75165439/145201835-2b37ff90-486e-4ee9-95f0-f599820393f2.png)

JER with Feywild
![with](https://user-images.githubusercontent.com/75165439/145201939-0c082044-9011-498e-988d-f72ce408227b.png)

I search the tag of drops，there are nothing，all of the drops disappear.
![final](https://user-images.githubusercontent.com/75165439/145202589-04c94375-44af-4ebb-9412-dcc90c82e498.png)

**Comment by SaphieNyako** [comment]
Yeh the dwarves have no drop. 
Also you have to reload your world for JER to work.
So the first time it wont show anything. 

![2021-12-08_12 53 48](https://user-images.githubusercontent.com/77398437/145204250-406f6e86-e662-492c-9808-ed45dc15fe29.png)

**Comment by CloudMeow** [comment]
I run the command /reload , then all is return to normal. I want to know why my modpack need to reload with these two mods. actually, I needn't reload without Feywild.  Of course,this problem harmless.
There is another problem. When I enter the dimension of Blue Skies Mod，there are BGM of Blue Skies and Feywild，sounds messy (although they all sound good).I have to set biome_music to false.
Even if there are these problems, I still enjoy this mod. =)

**Comment by SaphieNyako** [comment]
That's why there are configs. Lucky we have one so you can turn it off.
