### ISSUE TITLE
Add condition to recipes so they only are used when a specific mod is installed.

### ISSUE THREAD

**Issue by SaphieNyako** [SaphieNyako/Feywild#53]
add condition to recipes so they only are used when a specific mod is installed.
- botania
- mythicbotany
- ars_nouveau

example: 
"conditions": [
    {
      "type": "forge:mod_loaded",
      "modid": "ars_nouveau"
    }
  ]

This has already been added to 1.16 only has to be added to 1.17.

**Comment by noeppi-noeppi** [comment]
See #78
