### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by darkphan** [SaphieNyako/Feywild#6]
Version: feywild-1.16.5-1.2
Crash: https://gist.github.com/darkphan/e8d146feaea7cc6ffc20545bdb2a1046

**Comment by SaphieNyako** [comment]
Disabled the quests in the 1.2.1 update.
When we fix the problem another update will be done.

**Comment by SaphieNyako** [comment]
Uploaded 1.2.2 wich fixes the problem completely. 
No more crash, and Quest line is available again.
