### ISSUE TITLE
Update Patchouli

### ISSUE THREAD

**Issue by SaphieNyako** [SaphieNyako/Feywild#61]
* [x] Enable Patchouli for 1.17

* [x] Improve and add to excisting content
       - New Summons
       - Guide on how to handle your pixie

* [x] Add custom recipe by implementing Processors and templates

* [x] Make patchouli book translatable by adding to lang file.

* [x] Add new Wood Types

**Comment by SaphieNyako** [comment]
Made branch for this: https://github.com/SaphieNyako/Feywild/tree/dev/1.17---patchouli

**Comment by SaphieNyako** [comment]
Can't add to lang file. Thats why they have the translation maps.

**Comment by SaphieNyako** [comment]
The patchouli guide is missing the new Wood Types.

**Comment by noeppi-noeppi** [comment]
See #78
