### ISSUE TITLE
1.18 changes

### ISSUE THREAD

**Issue by noeppi-noeppi** [SaphieNyako/Feywild#63]
A collection of things that need to be changed when porting to 1.18.

**Comment by noeppi-noeppi** [comment]
The base entity classes are currently pretty complicated and confusing. So these should be cleaned up. Also the goals need cleaning up. There are many gaols which are very similar, one or two goal base classes might be required.

**Comment by SleepingCarcass** [comment]
Hi! When will the 1.18 version be ready approximately?

**Comment by noeppi-noeppi** [comment]
@SleepingCarcass We are using this issue to collect things that need to be changed in the code for 1.18, not as a progress tracker. That's why I'll delete your comment in a while to keep this issue clean

The 1.18 version is ready when it is ready, we are planning to port over in early January but no guarantee on that.

**Comment by SleepingCarcass** [comment]
thanks

пт, 24 дек. 2021 г., 19:38 noeppi_noeppi ***@***.***>:
