### ISSUE TITLE
Freeze with generate Feywild biome chunks

### ISSUE THREAD

**Issue by Edel-Lilies** [SaphieNyako/Feywild#66]
### Minecraft version

1.16.5

### Feywild version

1.16.5-2.0.7

### Forge version

36.2.22

### The latest.log file

no

### Issue description

Hi, your mod looks very beautiful and delicate,i put it in play with friends servers with 200+mods,maybe not your mod problem.
Generate Feywild biome's Chunks usually causes huge lag.If I use locatebiome and tp, game will freeze for about 10 seconds.
I went straight for a while,byg,environmental and cavesandcliffs 's biome won't be like this.

**Comment by SaphieNyako** [comment]
Sounds like a conflict with another mod.
We have our own modpack and servers and it runs fine. 
Do you have a link to your modpack or a list of mods?

**Comment by noeppi-noeppi** [comment]
Sorry to be that hard here but we have these issue form to help people fill good issue reports.
And if a field is marked as mandatory, that is for a reason.

So please fill out the missing fields. This is:

  * `The latest.log file`. If you have a good reason why you can't provide it, then outline that please.
  * `Other information` which says *such as modpacks, other mods and their versions* in the description. We need your mod list or modpack to help. FYI: You can copy the mod list to clipboard by running `/libx modlist` and clicking on the command output.

Keep in mind: You want us to help you, so we need the information requested. Thanks in advance.

**Comment by Edel-Lilies** [comment]
Thank you for enthusiastic,i packed debug and logs.
I play with Optifine,some resourcepacks and sharder ComplementaryShaders_v4.2.2 join Test server.

[logs.zip](https://github.com/SaphieNyako/Feywild/files/7765047/logs.zip)

**Comment by Edel-Lilies** [comment]
I deleted JustEnoughResources-1.16.5-0.12.1.133 and EnchantmentDescriptions-1.16.5-7.0.18 ,add mod chocolate-1.3.0-1.16.4,the lag disappeared.
Or maybe i changed resourcepacks?

**Comment by SaphieNyako** [comment]
Neither have anything to do with biome loading or related to the biomes.
I tried with both and it works fine.
First: Remove the shaders and try with out them.

Thanks!

**Comment by Edel-Lilies** [comment]
I have no problem now,Thanks your help!
