### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by EnotScript** [SaphieNyako/Feywild#7]
When loading the server, it gives an error:
[crash-2021-07-07_21.52.54-fml.txt](https://github.com/SaphieNyako/Feywild/files/6778322/crash-2021-07-07_21.52.54-fml.txt)

**Comment by Playelectro** [comment]
You are using v 1.2, issue should be fixed in v 1.2.2, please update the mod and see if the issue occurs again.

**Comment by EnotScript** [comment]
I updated it didn't help.

**Comment by EnotScript** [comment]
I'll try cleaning up the configs. One minute.

**Comment by EnotScript** [comment]
And everything helped. It was necessary to clear the configs.

**Comment by Playelectro** [comment]
hmmm could you send me the crash report now that you updated it
