### ISSUE TITLE
AI fixes for 1.18 port

### ISSUE THREAD

**Issue by SaphieNyako** [SaphieNyako/Feywild#72]
All the animations are out of sync since 1.18 port. 

* [x] Autumn Pixie
* [x] Spring Pixie
* [x] Summer Pixie
* [x] Winter Pixie
* [x] Dwarf
* [x] Mandragora
* [x] Shroomling

**Comment by SaphieNyako** [comment]
- Changed the particles for Spring Pixie casting, since the Totem of Undying effect just falls to the ground. Replaced it with hearts. 
- Added a message when trying to summon the Mandragora using a Magical Cookie on the mandrake. When not allied with Spring you will recieve a message saying the Mandrake won't take anything from you as long as you dont have the correct conditions. 
- Added a entry in Patchouli book showing you can change type of Mandragora using a Mandrake Seed. 
- Fixed Mandragora walk and idle animation being mixed up after change to speed.

**Comment by noeppi-noeppi** [comment]
See #78
