### ISSUE TITLE
As a User, I would like the ability to turn your title screen off. Please.

### ISSUE THREAD

**Issue by Seth0067** [SaphieNyako/Feywild#8]
Your title screen is a great thing for your pack community, but as a User, who makes his own kitchen sink instances, it is not appropriate for my content.  

We spoke briefly in your Discord chat yesterday and you indicated that you couldn't offer users this option based on your implementation path , and I spent an afternoon trying to get other solutions to work.  

I didn't necessarily want to create a title screen for my pack (a private instance), and thought simply replacing the screen with a panorama might be the easiest way to do this.  I tried downloading a simple panorama resource pack and loaded it as such, but this did not work to replace your title screen. I downloaded two different panorama mods ("Panorama" and "Panorama Creator") and neither of these were able to replace the screen. I then spent a not-insignificant amount of time messing with Fancy Menu (a fairly heavy solution for my use case) and this worked, but I don't believe that users should have to go to these lengths for something that should be a lot easier.

I decided to file this bug as an appeal to you to reconsider your approach.  "Ice and Fire" does a similar thing with their mod, and does allow users to turn this off in the cfg options.  

The link to their implementation is at [this link on their repo](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/client/gui/IceAndFireMainMenu.java)

Thanks - I really want to enjoy this mod, but right now my OCD is preventing me from doing so.  :)

**Comment by Playelectro** [comment]
Thank you for your feedback  😊

We are now working on version 1.3 and we will attempt to implement this feature in in that version. We have decided that a patch for this is **as of now** not a priority so this means you might have to wait a bit since we are cought up right now with implementing some future core mechanics. In the meantime switching the priority of the forge assets and the minecraft default pack from the resourcepack tab ingame should fix that issue.

In case more people want this feature added we will update its spot on our TODO list.

Please don't  be mad with us we are a small team and are trying our best to make a great mod 🥺

**Comment by Seth0067** [comment]
Just a heads up that at least in my pack, putting in a resource pack (supplying the game with a panorama) and making sure its placed above the mod resources, does not help to change the title screen to that panorama. I tried this with a created panorama pack, as well as one i downloaded for curseforge, with no luck. I also tried this in my big-ass kitchen sink pack and a pack stripped down to just JEI and Optifine. I can use Fancymenu as a short term solution, but just a heads up that the implementation may be problematic for some people.

**Comment by Seth0067** [comment]
Well - i found out why my personal panorama file AND the curseforge panorama failed - the overlay file wasn't included and not having that breaks the resource pack when using with mod resources (maybe?). For anyone else having this issue, i'm attaching the png that helps personal resource panoramas to work.
![panorama_overlay](https://user-images.githubusercontent.com/22122348/125210642-1c5c7280-e26f-11eb-84e3-b9287051e496.png)

**Comment by SaphieNyako** [comment]
1.2.4 has been released!
