### ISSUE TITLE
Supplementaries version mismatch

### ISSUE THREAD

**Issue by lexxieblack** [SaphieNyako/Feywild#80]
### Minecraft version

1.16.5

### Feywild version

2.0.6

### Forge version

36.2.23

### The latest.log file

https://pastebin.com/FWtKXAsE

### Issue description

Still an issue as #44 where the version is still not fixed. Supplementaries changed the way they write their versions, you need to update the mod to reflect this. It is unusable in its current state.

**Comment by SaphieNyako** [comment]
https://www.curseforge.com/minecraft/mc-mods/feywild/files/3550070
There is a 2.0.7 version now.

**Comment by lexxieblack** [comment]
For some reason this isn't showing up in my launcher.

**Comment by SaphieNyako** [comment]
what launcher are you using?

**Comment by lexxieblack** [comment]
GDLauncher

**Comment by lexxieblack** [comment]
Having some other difficulties with the launcher as well, mainly the console not working correctly to be able to debug things.
I'm trying to get help with the entire launcher but seems like they're not too eager to help people.

**Comment by lexxieblack** [comment]
I wonder if the file doesn't show up because of the CF API issues

**Comment by SaphieNyako** [comment]
Dont let anyone see this: But I think its easies to use CF app

**Comment by lexxieblack** [comment]
I'll have to find another way cuz there's no way I'm going to use that trash lol
Even during my time working on ATM, I always recommended people to stay away from it xd
