### ISSUE TITLE
Mod Needs Config settings in Minecraft Mod panel

### ISSUE THREAD

**Issue by yumikitzue** [SaphieNyako/Feywild#86]
### Minecraft version

1.16.5

### Feywild version

1.16.5-207

### Forge version

36.2.29

### The latest.log file

www.na.com

### Issue description

hello feywild creator your dwarf black smith needs a blacklist option in the mod section of mine craft menus the dwarf spam is so annoying they spawn constantly in the deep dark which is a different dimension made by anther mod creator

### Steps to reproduce

mods loaded (number Na) setting <---- needs config

### Other information

mods loaded (number Na) setting <---- needs config

**Comment by SaphieNyako** [comment]
We have a blacklist where you can add the dimension biome names so the mobs don't spawn. 
How ever some dimensions don't have biomes so you can't blacklist it. 
Also some dimensions make their buildings below the normal 64 height, wich causes the dwarves to spawn like crazy. 

We working on a solution:
Only make mobs spawn in the Overworld (and Alfheim) 
And add a whitelist that can add biomes where the mobs should spawn. 
I think this is much friendlier. 

Thanks for reporting. 
Leaving this open till solution is implemented.

**Comment by SaphieNyako** [comment]
Version 1.16.5 - 2.1.0 should fix this issue!
We added a whitelist instead of a blacklist, and the mobs only spawn in Overworld (and Alfheim) unless the biome of the dimension is added to the whitelist.
