### ISSUE TITLE
Wood slabs make stone sound

### ISSUE THREAD

**Issue by devjavu7** [SaphieNyako/Feywild#88]
### Minecraft version

1.16.5

### Feywild version

1.16.5-2.0.7

### Forge version

36.2.30

### The latest.log file

Not necessary

### Issue description

Stairs, slabs, fences and fence gates have the wrong placing/breaking sound. Sounds like stone.

**Comment by SaphieNyako** [comment]
Thanks for reporting. 
I kinda liked to poofy sound it makes so didnt notice. 
Will be changed next update.

**Comment by devjavu7** [comment]
Phanks <3

**Comment by SaphieNyako** [comment]
This will be changed in the 1.18.2 version update.
