### ISSUE TITLE
Library bell allows to easily spawn tons of iron golems and the library bell is global instead of per block.

### ISSUE THREAD

**Issue by noeppi-noeppi** [SaphieNyako/Feywild#9]
The library bell currently allows to spawn an infinite amount of iron golems by repeatedly right-clicking it.Even if the bell is broken, it will only kill the last golem spawned.

Also because the current state of the bell is stored in the block and not a block/tile entity, it is global for all bells in the world and the annoyance level is not saved on a restart. Also the annoyance level will never get really high if multiple people ring different bells alternately or a player leaves the end (because it will then be a new player object so the annoyance is reset).

To solve this issue, the library bell should be a block/tile entity and should only allow one golem to spawn ever. Possibly teleport it back to the bell if the player keeps clicking it.

**Comment by Playelectro** [comment]
Thanks for the feedback 😊

This is my fault.... adding the annoyance mechanic was kind of a last minute decision, the fix will be included in 1.3 when it comes out.

**Comment by SaphieNyako** [comment]
1.2.4 has been released
